# Generated by Django 3.2 on 2022-09-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('nombre', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(max_length=80)),
                ('correo', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
