# Generated by Django 3.2 on 2022-09-20 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('participantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrola', models.BooleanField()),
                ('fecha_enrola', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participantes.participante')),
            ],
        ),
    ]
