# Generated by Django 3.2 on 2022-09-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('enrolamientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolamiento',
            name='curso',
        ),
        migrations.AddField(
            model_name='enrolamiento',
            name='curso',
            field=models.ManyToManyField(to='cursos.Curso'),
        ),
    ]
